baseURL = "https://cousinstuff.com/"
languageCode = "en-us"
title = "CousinStuff"
enableRobotsTXT = true

[taxonomies]
  tag = "tags"

[params]
  brand = "CousinStuff"
  description = "A family recipe registry you can search, tag, and print."
  ogImage = "/img/og/og-corp.png"
  # optional if you want twitter tags:
  # twitter = "yourhandle"  # without @

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
